theme: jekyll-theme-cayman
title: "Mist Engine"
description: C++ Game Engine
name: "David Benages and Marina Albalà"
show_downloads: true
header:
  background-image: https://github.com/Vizalt/MistEngine/blob/main/docs/images/HeaderMist.PNG
